// Mocks generated by Mockito 5.1.0 from annotations
// in ditonton/test/tv_series/data/datasources/series_remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:ditonton/data/datasources/tv_series/series_remote_data_source.dart'
    as _i4;
import 'package:ditonton/data/models/tv_series/series_detail_model.dart' as _i3;
import 'package:ditonton/data/models/tv_series/series_model.dart' as _i6;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeClient_0 extends _i1.Fake implements _i2.Client {}

class _FakeTvSeriesDetailResponse_1 extends _i1.Fake
    implements _i3.TvSeriesDetailResponse {}

/// A class which mocks [TvSeriesRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSourceImpl extends _i1.Mock
    implements _i4.TvSeriesRemoteDataSourceImpl {
  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_0()) as _i2.Client);
  @override
  _i5.Future<List<_i6.TvSeriesModel>> getNowPlayingTvSeriess() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvSeriess, []),
              returnValue:
                  Future<List<_i6.TvSeriesModel>>.value(<_i6.TvSeriesModel>[]))
          as _i5.Future<List<_i6.TvSeriesModel>>);
  @override
  _i5.Future<_i3.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesDetail, [id]),
              returnValue: Future<_i3.TvSeriesDetailResponse>.value(
                  _FakeTvSeriesDetailResponse_1()))
          as _i5.Future<_i3.TvSeriesDetailResponse>);
  @override
  _i5.Future<List<_i6.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesRecommendations, [id]),
              returnValue:
                  Future<List<_i6.TvSeriesModel>>.value(<_i6.TvSeriesModel>[]))
          as _i5.Future<List<_i6.TvSeriesModel>>);
  @override
  _i5.Future<List<_i6.TvSeriesModel>> getPopularTvSeriess() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvSeriess, []),
              returnValue:
                  Future<List<_i6.TvSeriesModel>>.value(<_i6.TvSeriesModel>[]))
          as _i5.Future<List<_i6.TvSeriesModel>>);
  @override
  _i5.Future<List<_i6.TvSeriesModel>> getTopRatedTvSeriess() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvSeriess, []),
              returnValue:
                  Future<List<_i6.TvSeriesModel>>.value(<_i6.TvSeriesModel>[]))
          as _i5.Future<List<_i6.TvSeriesModel>>);
  @override
  _i5.Future<List<_i6.TvSeriesModel>> searchTvSeriess(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvSeriess, [query]),
              returnValue:
                  Future<List<_i6.TvSeriesModel>>.value(<_i6.TvSeriesModel>[]))
          as _i5.Future<List<_i6.TvSeriesModel>>);
}
